name: tutorial-quickstarts
on:
  schedule:
    - cron: "0 0/1 * * *"
  pull_request:
    branches:
      - main
    paths:
      - tutorials/quickstarts/**
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: pip install
      run: pip install -r requirements.txt
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ""
        auto-activate-base: true
    - name: Conda info
      shell: bash -l {0}
      run: conda info 
    - name: Run automl setup
      shell: bash -l {0}
      run: bash automl_setup_linux.sh
      working-directory: tutorials/quickstarts
    - name: Conda activate azureml_py36
      shell: bash -l {0}
      run: conda activate azureml_py36
    - name: Conda info
      shell: bash -l {0}
      run: conda info 
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run ClassificationWithAutomatedML.ipynb
      run: papermill ClassificationWithAutomatedML.ipynb - -k azureml_py36
      working-directory: tutorials/quickstarts
    - name: run AzureMLin10mins.ipynb
      shell: bash -l {0}
      run: papermill AzureMLin10mins.ipynb - -k azureml_py36
      working-directory: tutorials/quickstarts
    - name: run GettingStartedWithPythonSDK.ipynb
      run: papermill GettingStartedWithPythonSDK.ipynb - -k azureml_py36
      working-directory: tutorials/quickstarts