name: tutorial-quickstarts
on:
  schedule:
    - cron: "0 0/1 * * *"
  pull_request:
    branches:
      - main
    paths:
      - tutorials/quickstarts/**
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: pip install
      run: pip install -r requirements.txt
    - name: install conda
      uses: s-weigand/setup-conda@v1
    - name: create conda environment
      run: conda env create -f environment.yml
      working-directory: tutorials/quickstarts
    - name: install jupyter
      run: conda install -n azureml_py36 jupyter
    - name: activate conda environment
      run: source activate azureml_py36
      working-directory: tutorials/quickstarts
    - name: expose as kernel
      run: jupyter kernelspec install --user --name azureml_py36
      working-directory: tutorials/quickstarts
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run AzureMLin10mins.ipynb
      run: papermill AzureMLin10mins.ipynb - -k azureml_py36
      working-directory: tutorials/quickstarts
    - name: run GettingStartedWithPythonSDK.ipynb
      run: papermill GettingStartedWithPythonSDK.ipynb - -k azureml_py36
      working-directory: tutorials/quickstarts
    - name: run ClassificationWithAutomatedML.ipynb
      run: papermill ClassificationWithAutomatedML.ipynb - -k azureml_py36
      working-directory: tutorials/quickstarts